### ISSUE TITLE
User story 1: List of locations 

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#1]
## Value proposition

As a user, 
I want to see a list of all locations where I have bee colonies
in order to to have a good overview of them.  

## Description

![List of locations](https://user-images.githubusercontent.com/126454016/234341211-e6b50b13-7110-47c9-94ac-a8b9ba750b37.png)

## Acceptance criteria

- [ ] Header stays visible while scrolling
- [ ] For each location, one card is shown 
- [ ] Each card shows the name of the location
- [ ] Each card has the same size

## Tasks

- [ ] Create a branch
- [ ] Add a list component to the app
- [ ] Add a card component
- [ ] Add styling
