### ISSUE TITLE
User story 6: Add a ToDo page

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#13]
## Value proposition

As a user, 
I want to have a ToDo page where I can note down any tasks related to the bees 
in order to keep in mind everything. 

## Description
![ToDo page, new tasks can be entered, clicking on the checkbox of a ToDo lets it be crossed out and checked](https://user-images.githubusercontent.com/126454016/235201046-b430dce1-d8c2-423d-b077-5656a1c257fe.png)

## Acceptance criteria

- [ ] Header and nav bar visible 
- [ ] Task name and for each a checkbox shown 
- [ ] Clicking on checkbox lets task be crossed out and the checkbox is checked 
- [ ] Clicking on add button leads to a form where a new task can be entered
- [ ] Submitting the form redirects to the ToDo page where the new ToDo is shown 

## Tasks

- [ ] Create a new branch 
- [ ] Create ToDo page 
- [ ] Add list that contains tasks and checkboxes 
- [ ] Add add button that leads to form 
- [ ] Create a new page for form

**Comment by Roland-Hufnagel** [comment]
Hey Alena, you are really going fast foreward!
Your userstory is very clear and detailed. This looks very good. 

You should keep in mind, that US7 and US8 are big userstories. They may take some time to implement.
