### ISSUE TITLE
User story 14: Add text fields for general information on detail pages

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#15]
## Value proposition

As a user,
I want to add free text information on the locations' and colonies' detail pages 
in order to keep important notes directly on the concerned pages. 

## Description

![Free text field on locations' and colonies' detail pages](https://github.com/aaaleeenaaa/capstone-project-bee-organized/assets/126454016/86f121f3-0d66-4503-ae3c-d73bd589cd01)

## Acceptance criteria

- [ ] Header and nav bar visible all the time 
- [ ] Form for the free text is not submitted, the entered text just stays visible all the time

## Tasks

- [ ] Create a new branch 
- [ ] Create a form and add it on the respective detail pages

**Comment by CJAkkuec** [comment]
Nothing to add concerning the User Story itself, but maybe for future reference: perhaps it might be beneficial to think about the composition of the respective details pages. If there are a lot of colonies, then the location notes will be pushed way out of sight. To edit the notes, you'd have to scroll a fair amount in that case. Same goes for the colony details page. I'd probably move the notes to the top. 🤔

**Comment by aaaleeenaaa** [comment]
Thank you, that's a good point! I will definitely take that into consideration!

**Comment by aaaleeenaaa** [comment]
Small update: 
- Text fields directly under heading and not at the end of the respective pages
- Form is not submitted but entered text just stays visible
