### ISSUE TITLE
User story 10: Edit locations/bee colonies 

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#16]
## Value proposition

As a user,
I want to be able to edit the locations and bee colonies I added 
in order to keep them up to date if something changes. 

## Description

![Edit locations and colonies](https://user-images.githubusercontent.com/126454016/236416002-043b2720-fbbe-4f23-8a9b-a28ea402264c.png)

## Acceptance criteria

- [ ] Header and nav bar visible all the time 
- [ ] Edit buttons visible on all location and bee colony cards
- [ ] Click on edit button lets the user rename the location/colony

## Tasks

- [ ] Create a new branch 
- [ ] Add edit buttons with according functionality

**Comment by CJAkkuec** [comment]
Technically there's nothing "wrong" about this, but you accidentally fused two user stories into one. 🤔 Editing content (the U in CRUD) is a feature, and deleting content (the D in CRUD) is a separate feature, so this user story would have to be split in two. ✌️

**Comment by t0bbl** [comment]
LGTM
