### ISSUE TITLE
User story 8: Save data

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#18]
## Value proposition

As a user, 
I want to be able to reaccess the data I entered on the page 
in order to actually save all information and to not have to enter it again. 

## Description

All data entered is saved and can be reaccessed when reopening the page. This concerns all locations and bee colonies as well as the information about them (e.g. the data in the checklists on the colonies' detail pages). 

## Acceptance criteria

- [ ] Entered locations, bee colonies and other data are shown again when reopening the page 

## Tasks

- [ ] Create a new branch 
- [ ] Implement local storage usage for all data
