### ISSUE TITLE
User story 2: Add locations to the list 

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#2]
## Value proposition

As a user, 
I want to add locations with bee colonies to the list
in order to have a good, up to date overview of all of my locations. 

## Description

![Clicking on add button leads to form where a new location can be entered, submitting the form leads to the new location being shown in the list](https://user-images.githubusercontent.com/126454016/234342473-f46f18ed-4b94-46b4-8dc2-47b1e3c5465a.png)

## Acceptance criteria

- [ ] Header stays visible all the time
- [ ] Click on add button leads to a form where a new location can be entered
- [ ] Submitting the form leads to the new location being shown in the list 
- [ ] Form cannot be empty when being submitted 
- [ ] Add button always visible on list page but not on page with form 

## Tasks

- [ ] Create a branch
- [ ] Add an add button to page with list
- [ ] Add a form with label, text field and submit button
- [ ] Click on add button leads to the form
- [ ] Submitting the form leads to the new location being shown in the list
- [ ] Add styling

**Comment by PacoSchwab** [comment]
LGTM and nice app idea! Hint: If you want to apply advanced styling to the form, it could be part of another US.
