### ISSUE TITLE
User story 11:  Delete locations/bee colonies 

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#21]
## Value proposition

As a user,
I want to be able to delete the locations and bee colonies I added
in order to keep them up to date if something changes.

## Description

![Delete locations and bee colonies](https://user-images.githubusercontent.com/126454016/236417259-ab4f3ec1-94f2-47bd-b456-30117c36bb70.png)

## Acceptance criteria

- [ ] Header and nav bar visible all the time 
- [ ] Delete buttons visible on all location and bee colony cards
- [ ] Click on delete button lets the respective item disappear from list

## Tasks

- [ ] Create a new branch 
- [ ] Add delete buttons with according functionality

**Comment by t0bbl** [comment]
LGTM
maybe you want to add a "toggle edit/delete" button later on to keep the visuals a little simpler. just a note, nothing you need to fix in this US.
