### ISSUE TITLE
User story 13: Weather page

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#23]
## Value proposition

As a user,
I want to see a page with the current and forecasted weather 
in order to be able to plan my activities according to the conditions (as some tasks might be better done without rain, when it is not too hot etc.).

## Description

![Weather page with today's and forecasted weather conditions ](https://user-images.githubusercontent.com/126454016/236830543-6cbd9748-b24d-4d23-814a-18231b830673.png)

## Acceptance criteria

- [ ] A search bar to enter the place the weather should be shown for at the top of the page 
- [ ] Today's date and the dates of the upcoming days are shown 
- [ ] Temperature as well as rain probability are shown 
- [ ] A symbol that best describes the day's weather is shown 

## Tasks

- [ ] Create a new branch 
- [ ] Fetch data from weather API
- [ ] Implement search bar

**Comment by HenrikeStahlhut** [comment]
Looks very nice ☀️ just one tiny thing would be to highlight today's date maybe :)
