### ISSUE TITLE
User story 12: Delete ToDos

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#24]
## Value proposition

As a user,
I want to be able to delete ToDos I added
in order to keep the ToDo List up to date and to delete no longer important tasks

## Description

![Delete option for ToDos](https://user-images.githubusercontent.com/126454016/236835445-ef1df39c-ca75-4bb3-ae1d-ec068f0faf49.png)

## Acceptance criteria

- [ ] Behind each ToDo, a button to delete it is shown 
- [ ] Clicking on the button lets the ToDo disappear from the list 

## Tasks

- [ ] Create a new branch 
- [ ] Add a delete button to each ToDo
- [ ] Implement the delete function accordingly

**Comment by HenrikeStahlhut** [comment]
LGTM 🕺
