### ISSUE TITLE
User story 3: List of bee colonies for each location 

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#3]
## Value proposition

As a user, 
I want to have a list of the bee colonies I have at each location
in order to have an overview of how many bee colonies I have at which place.

## Description

![Clicking on a location leads to a detail page with bee colonies](https://user-images.githubusercontent.com/126454016/234345549-95044671-ffc8-44a6-bb1a-bd0b7ae14d0b.png)

## Acceptance criteria

- [ ] Header stays visible all the time
- [ ] Click on location leads to list of colonies there
- [ ] List heading shows name of location 
- [ ] For each bee colony, one card is shown 
- [ ] Each card shows the name of the bee colony
- [ ] Each card has the same size

## Tasks

- [ ] Create a branch
- [ ] Create a detail page for each location
- [ ] Click on location leads to detail page
- [ ] Create list for detail page
- [ ] Add heading and cards to list

**Comment by t0bbl** [comment]
sounds great!
