### ISSUE TITLE
User story 15: Upload images 

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#31]
## Value proposition

As a user, 
I want to have the opportunity to upload images of my bee colonies
in order to store information not just via words but also visually. 

## Description

On the colonies' detail pages below the checklist, a field to upload images is implemented. The uploaded images are shown underneath. 

## Acceptance criteria

- [ ] On the colonies' detail pages, an option to upload images is shown
- [ ] The uploaded images are shown underneath
- [ ] The uploaded images are displayed in a visually appealing way (not distorted or blurred)

## Tasks

- [ ] Create a new branch 
- [ ] Implement an option to upload images with cloudinary
- [ ] Implement a section where the uploaded images are shown

**Comment by Leukipos** [comment]
Looks good to me. may the force be with you! ;)
