### ISSUE TITLE
User story 16: Bee colony checks 

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#34]
## Value proposition

As a user, 
I want to keep track of when I last checked a bee colony and when the next check is due
in order to be able to check all my bee colonies on a regular basis. 

## Description

![check dates for bee colonies are kept track of](https://github.com/aaaleeenaaa/capstone-project-bee-organized/assets/126454016/db5d6a4f-820b-4391-8e71-8afb4bda6b43)

## Acceptance criteria

- [ ] On the bee colony detail page, I can enter the date when I last checked it 
- [ ] Moreover, I can enter the date when the next check is due
- [ ] On the to do list page, underneath the ToDos, all due check dates are listed (dates + corresponding colony) 

## Tasks

- [ ] Create a new branch 
- [ ] Implement input fields with type "date" on bee colonies' detail page 
- [ ] Create section on ToDo List page where all dates when checks are due are listed

**Comment by MerleMak** [comment]
Very nice!! The Bees will thank you for this feature :D :)
