### ISSUE TITLE
User story 17: List of material 

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#36]
## Value proposition

As a user,
I want to keep track of which material I have at which location 
in order to have an overview of my equipment. 

## Description

Bee keepers estimate to have about 10 to 15 positions of equipment at each of their locations. They should be visible at one glance without scrolling. Hence, a textarea with 15 rows is needed. This should be displayed underneath the general notes for each location. 

## Acceptance criteria

- [ ] Textarea with 15 lines underneath the general notes on each location's detail page 
- [ ] Above the textarea, there is a descriptive label 
- [ ] Entries are saved in local storage and displayed again when the page is reopened 

## Tasks

- [ ] Create a new branch 
- [ ] Implement a labelled textarea

**Comment by doctype-Melvin** [comment]
Keep it organized, I like that!
Much success!
