### ISSUE TITLE
User story 4: Add bee colonies to list on detail page of each location 

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#4]
## Value proposition

As a user, 
I want to add bee colonies to the detail page of each location
in order to have an up to date overview of how many colonies I have at which location.

## Description

![Clicking on a location leads to its detail page where a new bee colony can be added](https://user-images.githubusercontent.com/126454016/234592038-226f989e-949b-4c7f-bae7-af5310681d59.png)

## Acceptance criteria

- [ ] Header stays visible all the time
- [ ] Click on add button leads to form where a new bee colony can be entered 
- [ ] Form cannot be empty when being submitted 
- [ ] Submitting the form leads to the new bee colony being shown in the location's detail page list

## Tasks

- [ ] Create a branch
- [ ] Add an add button to location's detail page
- [ ] Add a form with label, text field and submit button

**Comment by Roland-Hufnagel** [comment]
Hi Alena, your userstories look very professional! Great 💪

Just little suggestions:

- I think the left view in the wireframe is not part of this US and can be deleted from the wireframe
- Where the button and submit leads to is not a task but an acceptence criteria (as you mentioned). Please delete this from the tasks

**Comment by Roland-Hufnagel** [comment]
Very nice!
