### ISSUE TITLE
User story 5: Add detail page for each bee colony 

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#5]
## Value proposition

As a user
I want to have a detail page with a checklist for each bee colony 
in order to easily keep hold of information about them. 

## Description

![Clicking on a colony leads to its detail page with a heading and question cards](https://user-images.githubusercontent.com/126454016/236158352-898ba63e-d286-415e-97ee-5f4cfd1ecda3.png)

## Acceptance criteria

- [ ] Header stays visible all the time
- [ ] Click on colony leads to its detail page
- [ ] Detail page contains list with heading and question cards
- [ ] Heading contains name of colony
- [ ] Question cards contain question and answer options depending on type of question (checkboxes, textfield etc.) 

## Tasks

- [ ] Create a branch
- [ ] Create a detail page for each colony
- [ ] Create a card component with questions and answer options
- [ ] Add list with heading and cards to the colony's detail page

**Comment by BenRodProd** [comment]
LGTM

**Comment by aaaleeenaaa** [comment]
Small update (heading containing only colony and not the location as well)

**Comment by aaaleeenaaa** [comment]
Small update (just removed submit button of question with text field as when saving the answers is implemented in another user story, the given answers should appear again within the form)
