### ISSUE TITLE
User story 9: Add overview page

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#7]
## Value proposition

As a user,
I want to have an overview page listing all my locations and bee colonies 
in order to see the total amount of them at one glance. 

## Description

![Overview page showing all locations and their bee colonies](https://user-images.githubusercontent.com/126454016/234576218-e16ae948-6d23-4546-aad8-0814419b337d.png)

## Acceptance criteria

- [ ] Header stays visible all the time
- [ ] Page contains one card for each location
- [ ] Each card contains the name of the location and of the bee colonies
- [ ] Clicking on the location leads to the corresponding detail page
- [ ] Clicking on the bee colonies leads to their corresponding detail pages with their checklists

## Tasks

- [ ] Create a branch
- [ ] Create a new page
- [ ] Add card component that contains location and its bee colonies 
- [ ] Link the locations to their detail page
- [ ] Link the colonies to their detail page
