### ISSUE TITLE
User story 7: Add navigation 

### ISSUE THREAD

**Issue by aaaleeenaaa** [aaaleeenaaa/capstone-project-bee-organized#8]
## Value proposition

As a user, 
I want to be able to navigate between the pages
in order to easily reach all of them.

## Description

![Add navbar as well as "back" links on detail pages](https://user-images.githubusercontent.com/126454016/235682469-c53245d2-c2d6-4f07-8951-b0b300b714a6.png)

## Acceptance criteria

- [ ] Nav bar visible on every page
- [ ] Icon for current page is highlighted
- [ ] "Back" links on detail pages 
- [ ] All links lead to the right pages 

## Tasks

- [ ] Create a branch 
- [ ] Create a nav bar 
- [ ] Use nav bar in layout component so that it is visible on every page
- [ ] Create "back" links
